### ISSUE TITLE
Can't detect app in second line

### ISSUE THREAD

**Issue by RomainEndelin** [iamale/dokku-monorepo#4]
Hi,

I am trying to use this plugin, but I'm facing an issue. When I want to deploy the first app (`web`) it works. But when I want to deploy the second one (`api`), I get the following error:

```
remote: =====> Monorepo detected
remote: =====> The application clarity_api is not defined in .dokku-monorepo!
```

It seems to be caused by line number: if I reverse my `.monorepo` file, with `api` on the first line and `web` on the second line, then `web` will be the one that fails.

---

My `.monorepo`:
```
clarity_web=web
clarity_api=api
```

I also tried:
```
web=web
api=api
```

My folders structure:
```
web/
api/
.monorepo
```

`git remote -v`:
```
dokku-api       dokku@clarity_dokku:clarity_api (fetch)
dokku-api       dokku@clarity_dokku:clarity_api (push)
dokku-web       dokku@clarity_dokku:clarity_web (fetch)
dokku-web       dokku@clarity_dokku:clarity_web (push)
```

Thanks

**Comment by iamale** [comment]
Thanks for reporting this, Romain!

I've tried running the plugin manually with your `.dokku-monorepo` and it worked well for both apps. Please note that the filename is `.dokku-monorepo` and not just `.monorepo`! If it is correct (I assume it is, as the plugin wouldn't be triggered otherwise), could you please provide a redacted (without any private code) reproduction, i. e. as a repository here on GitHub?

**Comment by RomainEndelin** [comment]
Thanks for the feedback @iamale, it turns out the problem was with blank line at the end. `read` considers that a line is broken if it doesn't end with a new-line character.

So the quick workaround is to add a blank line at the end of `.dokku-monorepo`, and I've also created a PR to parse it anyway (even with no blank line).

PS. Sure, it was `.dokku-monorepo`, not `.monorepo`, my bad ;)

**Comment by iamale** [comment]
Thank you! It's a bit strange, I believe I have tested without newline at end as well, but maybe something slipped my eye. I'll review and merge your PR tonight!

**Comment by sam3d** [comment]
@iamale safe to close this issue?

**Comment by iamale** [comment]
Yep, thanks for a reminder!
